root = "."
tmp_dir = "tmp"

[build]
args_bin = []
entrypoint = "./tmp/server"
cmd = "mise run build"
delay = 1000
exclude_dir = ["tmp", "logs"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ\\.go$", "^models/shared/icons/icons\\.templ$", "^models/shared/icons/registry\\.templ$"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ", "yaml", "yml"]
kill_delay = "0s"
send_interrupt = false
stop_on_root = false

[log]
time = false
main_only = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
